//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formation
    {
        public Formation(string libelle, DateTime? dateDebut, DateTime? dateFin, int? idFormateur, int? idType)
        {
            Libelle = libelle;
            DateDebut = dateDebut;
            DateFin = dateFin;
            IdFormateur = idFormateur;
            IdType = idType;
        }

        public int Id { get; set; }
        public string Libelle { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<int> IdFormateur { get; set; }
        public Nullable<int> IdType { get; set; }
    
        public virtual Enseignant Enseignant { get; set; }
        public virtual TypeFormation TypeFormation { get; set; }
    }
}
