//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeFormation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeFormation()
        {
            this.Formations = new HashSet<Formation>();
        }

        public TypeFormation(string type)
        {
            this.type = type;
        }

        public int IdType { get; set; }
        public string type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formation> Formations { get; set; }

        public override string ToString()
        {
            string domaineFormation = "ID TYPE : " + IdType +" /  "+" Domaine : "+ type + "\n";
            return domaineFormation;
        }
    }
}
